# Generated by Django 2.0.7 on 2022-03-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='제목')),
                ('url', models.URLField(unique=True, verbose_name='주소')),
                ('writer', models.CharField(max_length=20, verbose_name='작성자')),
            ],
        ),
    ]
