# Generated by Django 4.0.3 on 2022-04-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('explanation', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='%Y/%m/%d')),
                ('type', models.CharField(choices=[('photo', 'photo'), ('painting', 'painting'), ('sculpture', 'sculpture'), ('video', 'video'), ('print', 'print')], default='photo', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
