version: "3"

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespw
    volumes:
      - ./postgresDB:/var/lib/postgresql/data
  
  was:
    container_name: django_gunicorn
    build: .
    command: supervisord -c supervisord.conf
    ports:
      - "8000:8000"
      - "9001:9001"
    expose:
      - 8001
    volumes:
      - .:/app
    depends_on:
      - db

  server:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/dockerfile
    ports:
      - "8002:80"
    depends_on:
      - was